-- GENERATED by supabase/prepare-source-oauth.mjs; do not edit this bundle.
-- Run ONCE as postgres in efibfevyiepkwpnobaro SQL Editor.
-- Requires the existing v7 school and its real manager; creates no accounts.
-- Existing educational data, login, TOTP and native OAuth guard are preserved.
-- All additions and the service permission fix commit together or roll back.
begin;

do $source_oauth_preflight$
declare required text; collision boolean;
begin
  if current_user not in ('postgres','supabase_admin') then
    raise exception 'SOURCE_OAUTH_REQUIRES_DATABASE_OWNER';
  end if;
  foreach required in array array['anon','authenticated','service_role'] loop
    if not exists(select 1 from pg_roles where rolname=required) then
      raise exception 'SOURCE_OAUTH_ROLE_MISSING: %', required;
    end if;
  end loop;
  foreach required in array array['public.profiles','public.audit_logs',
    'public.classes','public.grade_levels','public.subjects','public.class_students',
    'public.teacher_assignments','public.scores','public.school_settings','public.assignments',
    'auth.users','auth.sessions','auth.mfa_factors'] loop
    if to_regclass(required) is null then
      raise exception 'SOURCE_OAUTH_EXISTING_TABLE_MISSING: %', required;
    end if;
  end loop;
  foreach required in array array['public.account_ready()','public.is_manager()',
    'public.teacher_has_access(uuid,uuid)','public.can_read_class(uuid)',
    'public.can_read_student(uuid)','public.oauth_postgrest_guard()',
    'pg_catalog.gen_random_uuid()'] loop
    if to_regprocedure(required) is null then
      raise exception 'SOURCE_OAUTH_EXISTING_FUNCTION_MISSING: %', required;
    end if;
  end loop;
  if exists(select 1 from (values
    ('users','id'),('users','encrypted_password'),
    ('sessions','id'),('sessions','user_id'),('sessions','aal'),('sessions','factor_id'),('sessions','not_after'),
    ('mfa_factors','id'),('mfa_factors','user_id'),('mfa_factors','status'),('mfa_factors','factor_type')
    ) as needed(table_name,column_name)
    where not exists(select 1 from information_schema.columns c
      where c.table_schema='auth' and c.table_name=needed.table_name and c.column_name=needed.column_name)) then
    raise exception 'SOURCE_OAUTH_NATIVE_AUTH_VERSION_UNSUPPORTED';
  end if;
  if exists(select 1 from (values ('must_change_password'),('password_changed_at')) as needed(column_name)
    where not exists(select 1 from information_schema.columns c
      where c.table_schema='public' and c.table_name='profiles' and c.column_name=needed.column_name)) then
    raise exception 'SOURCE_OAUTH_REQUIRES_EXISTING_V7_PROFILES';
  end if;
  if not exists(select 1 from public.profiles p join auth.users u on u.id=p.id
    where p.role='manager' and p.active and not p.must_change_password
      and (nullif(to_jsonb(u)->>'banned_until','') is null
        or (to_jsonb(u)->>'banned_until')::timestamptz<=clock_timestamp())
      and nullif(to_jsonb(u)->>'deleted_at','') is null) then
    raise exception 'SOURCE_OAUTH_REQUIRES_EXISTING_READY_MANAGER';
  end if;
  if exists(select 1 from pg_namespace where nspname='system_oauth')
    or to_regprocedure('public.oauth_operation(text,jsonb)') is not null
    or to_regprocedure('public.oauth_api(text,text,jsonb)') is not null
    or to_regprocedure('public.oauth_cleanup()') is not null
    or to_regprocedure('public.assert_manager_session(uuid,uuid)') is not null
    or exists(select 1 from pg_trigger where
      (tgrelid='public.profiles'::regclass and tgname='oauth_profile_security')
      or (tgrelid='auth.users'::regclass and tgname='oauth_auth_security')) then
    raise exception 'SOURCE_OAUTH_ALREADY_INSTALLED_OR_NAME_COLLISION';
  end if;
  if exists(select 1 from pg_extension where extname='pg_cron') then
    execute 'select exists(select 1 from cron.job where jobname=''system-oauth-cleanup'')' into collision;
    if collision then raise exception 'SOURCE_OAUTH_CLEANUP_JOB_COLLISION'; end if;
  end if;
end $source_oauth_preflight$;

-- Source: supabase/migrations/20261007_oauth_connector.sql
-- SHA-256: 60168e1071c71f912f95f1cce16fabe9829a4b7ec88d62bc8ce8c5a6a21b78f7
-- Additive OAuth connector. Run after all four v7 migrations.
-- Only the authenticated Edge Function service client may call these RPCs.
-- Browser credentials, raw codes/tokens/client secrets and MFA secrets never enter this schema.

create schema system_oauth;
revoke all on schema system_oauth from public,anon,authenticated,service_role;

create table system_oauth.clients(
 client_id text primary key check(client_id ~ '^[A-Za-z0-9._-]{8,128}$'),
 name text not null check(length(name) between 1 and 120),
 redirect_uris text[] not null check(cardinality(redirect_uris) between 1 and 10),
 allowed_scopes text[] not null check(cardinality(allowed_scopes) between 1 and 4),
 secret_hash text check(secret_hash ~ '^[a-f0-9]{64}$'),
 public_client boolean not null,pkce_required boolean not null default true,
 active boolean not null default true,created_at timestamptz not null default clock_timestamp(),updated_at timestamptz not null default clock_timestamp(),
 check(not public_client or (secret_hash is null and pkce_required)),
 check(public_client or secret_hash is not null)
);
create table system_oauth.requests(
 id uuid primary key,client_id text not null references system_oauth.clients,
 user_id uuid not null references public.profiles on delete cascade,session_id uuid not null,
 redirect_uri text not null,scopes text[] not null,state text not null,
 code_challenge text,csrf_hash text not null check(csrf_hash ~ '^[a-f0-9]{64}$'),
 created_at timestamptz not null default clock_timestamp(),expires_at timestamptz not null default clock_timestamp()+interval '10 minutes',
 decided_at timestamptz
);
create table system_oauth.grants(
 id uuid primary key default gen_random_uuid(),client_id text not null references system_oauth.clients,
 user_id uuid not null references public.profiles on delete cascade,scopes text[] not null,
 role_at_issue public.user_role not null,mfa_verified_at timestamptz,mfa_factor_id uuid,
 created_at timestamptz not null default clock_timestamp(),last_used_at timestamptz,revoked_at timestamptz
);
create index oauth_grant_user on system_oauth.grants(user_id,client_id) where revoked_at is null;
create table system_oauth.codes(
 code_hash text primary key check(code_hash ~ '^[a-f0-9]{64}$'),grant_id uuid not null references system_oauth.grants on delete cascade,
 redirect_uri text not null,code_challenge text,
 created_at timestamptz not null default clock_timestamp(),expires_at timestamptz not null default clock_timestamp()+interval '120 seconds',consumed_at timestamptz
);
create table system_oauth.access_tokens(
 token_hash text primary key check(token_hash ~ '^[a-f0-9]{64}$'),grant_id uuid not null references system_oauth.grants on delete cascade,
 scopes text[] not null,created_at timestamptz not null default clock_timestamp(),expires_at timestamptz not null default clock_timestamp()+interval '900 seconds'
);
create table system_oauth.refresh_tokens(
 token_hash text primary key check(token_hash ~ '^[a-f0-9]{64}$'),grant_id uuid not null references system_oauth.grants on delete cascade,
 scopes text[] not null,created_at timestamptz not null default clock_timestamp(),expires_at timestamptz not null,consumed_at timestamptz
);
create index oauth_access_grant on system_oauth.access_tokens(grant_id);
create index oauth_refresh_grant on system_oauth.refresh_tokens(grant_id);
create table system_oauth.rate_limits(key text primary key,count integer not null,started_at timestamptz not null);
create index oauth_rate_age on system_oauth.rate_limits(started_at);
do $$ declare t text; begin
 foreach t in array array['clients','requests','grants','codes','access_tokens','refresh_tokens','rate_limits'] loop
  execute format('alter table system_oauth.%I enable row level security',t);
  execute format('revoke all on system_oauth.%I from public,anon,authenticated,service_role',t);
 end loop;
end $$;

create function system_oauth.strings(p jsonb) returns text[]
language sql immutable set search_path=pg_catalog
as $$ select coalesce(array_agg(distinct x order by x),array[]::text[]) from jsonb_array_elements_text(p) x $$;
create function system_oauth.audit(p_user uuid,p_action text,p_record text,p_meta jsonb default '{}') returns void
language sql set search_path=public,pg_catalog
as $$ insert into public.audit_logs(user_id,action,table_name,record_id,new_data)
 values(p_user,p_action,'oauth',p_record,p_meta) $$;
create function system_oauth.live_user(p_user uuid) returns boolean
language sql volatile security definer set search_path=public,pg_catalog
as $$ select exists(select 1 from public.profiles p join auth.users u on u.id=p.id
 where p.id=p_user and p.active and not p.must_change_password
 and (nullif(to_jsonb(u)->>'banned_until','') is null or (to_jsonb(u)->>'banned_until')::timestamptz<=clock_timestamp())
 and nullif(to_jsonb(u)->>'deleted_at','') is null) $$;
create function system_oauth.browser_error(p_user uuid,p_mfa numeric,p_session uuid) returns text
language plpgsql volatile security definer set search_path=public,pg_catalog
as $$ declare s auth.sessions; begin
 if not system_oauth.live_user(p_user) then return 'account_not_ready'; end if;
 -- /auth/v1/user validates a signed JWT but does not compare its AAL with the
 -- mutable Auth session. A recent old aal2 JWT must not outlive MFA downgrade.
 -- Only the session row is locked: GoTrue can delete a factor before updating
 -- its sessions, so locking the factor too would introduce the reverse order.
 -- Native legacy MFA verification may lock a session before updating auth.users.
 -- Never wait on that session while holding the opposite identity row lock.
 select * into s from auth.sessions where id=p_session and user_id=p_user for share nowait;
 if not found or (s.not_after is not null and s.not_after<=clock_timestamp()) then return 'invalid_token'; end if;
 if exists(select 1 from public.profiles where id=p_user and role='manager')
 and (p_mfa is null or p_mfa<extract(epoch from clock_timestamp()-interval '10 minutes') or p_mfa>extract(epoch from clock_timestamp()+interval '30 seconds')
  or s.aal is distinct from 'aal2' or not exists(select 1 from auth.mfa_factors f
   where f.id=s.factor_id and f.user_id=p_user and f.status='verified' and f.factor_type='totp'))
 then return 'mfa_required'; end if;
 return null;
exception when lock_not_available then return 'temporarily_unavailable';
end $$;
create function system_oauth.grant_live(p_grant system_oauth.grants) returns boolean
language sql volatile security definer set search_path=public,pg_catalog
as $$ select p_grant.revoked_at is null and system_oauth.live_user(p_grant.user_id)
 and exists(select 1 from system_oauth.clients where client_id=p_grant.client_id and active and p_grant.scopes<@allowed_scopes)
 and exists(select 1 from public.profiles where id=p_grant.user_id and role=p_grant.role_at_issue
 and (role<>'manager' or (p_grant.mfa_verified_at is not null and exists(select 1 from auth.mfa_factors f
  where f.id=p_grant.mfa_factor_id and f.user_id=p_grant.user_id and f.status='verified' and f.factor_type='totp')))) $$;
create function system_oauth.revoke_grant(p_id uuid) returns void
language sql set search_path=pg_catalog
as $$ update system_oauth.grants set revoked_at=coalesce(revoked_at,clock_timestamp()) where id=p_id $$;
-- Security writers already own an identity/client row; disconnect owns the
-- app/user advisory lock. Lock all grants in one deterministic order, then all
-- pending requests. Child credentials are invalidated through their parent,
-- without acquiring leaf locks that exchange/refresh/API take before grants.
create function system_oauth.revoke_matching(p_user uuid default null,p_client text default null) returns void
language plpgsql set search_path=pg_catalog
as $$ begin
 perform id from system_oauth.grants
 where (p_user is null or user_id=p_user) and (p_client is null or client_id=p_client)
 order by id for update;
 update system_oauth.grants set revoked_at=coalesce(revoked_at,clock_timestamp())
 where (p_user is null or user_id=p_user) and (p_client is null or client_id=p_client);
 perform id from system_oauth.requests
 where (p_user is null or user_id=p_user) and (p_client is null or client_id=p_client)
 order by id for update;
 update system_oauth.requests set decided_at=coalesce(decided_at,clock_timestamp())
 where (p_user is null or user_id=p_user) and (p_client is null or client_id=p_client);
end $$;
create function system_oauth.profile_security_changed() returns trigger
language plpgsql security definer set search_path=public,pg_catalog
as $$ begin
 if new.active is distinct from old.active or new.role is distinct from old.role
 or new.must_change_password is distinct from old.must_change_password or new.password_changed_at is distinct from old.password_changed_at then
  perform system_oauth.revoke_matching(new.id,null);
 end if;return new;
end $$;
create trigger oauth_profile_security after update on public.profiles for each row execute function system_oauth.profile_security_changed();
create function system_oauth.auth_security_changed() returns trigger
language plpgsql security definer set search_path=public,pg_catalog
as $$ begin
 if new.encrypted_password is distinct from old.encrypted_password
 or to_jsonb(new)->>'banned_until' is distinct from to_jsonb(old)->>'banned_until'
 or to_jsonb(new)->>'deleted_at' is distinct from to_jsonb(old)->>'deleted_at' then
  perform system_oauth.revoke_matching(new.id,null);
 end if;return new;
end $$;
create trigger oauth_auth_security after update on auth.users for each row execute function system_oauth.auth_security_changed();

-- This is a trusted service boundary, not a browser RPC. Edge verifies JWT signature,
-- subject, session_id and AMR MFA timestamp before supplying user/actor/mfa_time.
-- Client authentication and S256 hashing are performed by the Edge Function.
create function public.oauth_operation(p_action text,p_data jsonb) returns jsonb
language plpgsql security definer set search_path=public,pg_catalog
as $$ declare
 c system_oauth.clients;r system_oauth.requests;g system_oauth.grants;
 code system_oauth.codes;rt system_oauth.refresh_tokens;at system_oauth.access_tokens;
 uid uuid;actor uuid;scope_list text[];uris text[];err text;gid uuid;
 mfa numeric;rate_count integer;rate_start timestamptz;rate_limit integer;rate_window integer;answer jsonb;
begin
 if current_setting('transaction_isolation')<>'read committed' then raise exception 'OAuth requires READ COMMITTED isolation'; end if;
 if p_data is null or jsonb_typeof(p_data)<>'object' then return jsonb_build_object('error','invalid_request'); end if;
 if p_action='rate' then
  if length(coalesce(p_data->>'key','')) not between 1 and 256 then return jsonb_build_object('error','invalid_request'); end if;
  rate_limit:=(p_data->>'limit')::integer;rate_window:=(p_data->>'window_seconds')::integer;
  if rate_limit not between 1 and 1000 or rate_window not between 1 and 3600 then return jsonb_build_object('error','invalid_request'); end if;
  insert into system_oauth.rate_limits(key,count,started_at) values(p_data->>'key',1,clock_timestamp())
  on conflict(key) do update set
   count=case when system_oauth.rate_limits.started_at<=clock_timestamp()-make_interval(secs=>rate_window) then 1 else system_oauth.rate_limits.count+1 end,
   started_at=case when system_oauth.rate_limits.started_at<=clock_timestamp()-make_interval(secs=>rate_window) then clock_timestamp() else system_oauth.rate_limits.started_at end
  returning count,started_at into rate_count,rate_start;
  return jsonb_build_object('allowed',rate_count<=rate_limit,'retry_after',greatest(1,ceil(extract(epoch from rate_start+make_interval(secs=>rate_window)-clock_timestamp()))));
 end if;
 if p_action='client' then
  select * into c from system_oauth.clients where client_id=p_data->>'client_id' and active;
  if not found then return jsonb_build_object('error','invalid_client'); end if;
  return to_jsonb(c)-'created_at'-'updated_at';
 end if;
 if p_action in ('register','client_disable') then
  actor:=(p_data->>'actor')::uuid;mfa:=(p_data->>'mfa_time')::numeric;
  perform 1 from auth.users where id=actor for share;
  perform 1 from public.profiles where id=actor for share;
  err:=system_oauth.browser_error(actor,mfa,(p_data->>'session_id')::uuid);
  if err is not null then return jsonb_build_object('error',err); end if;
  if not exists(select 1 from public.profiles where id=actor and role='manager') then return jsonb_build_object('error','access_denied'); end if;
  if p_action='client_disable' then
   update system_oauth.clients set active=false,updated_at=clock_timestamp() where client_id=p_data->>'client_id';
   perform system_oauth.revoke_matching(null,p_data->>'client_id');
   perform system_oauth.audit(actor,'OAUTH_CLIENT_DISABLED',p_data->>'client_id');
   return jsonb_build_object('ok',true);
  end if;
  if jsonb_typeof(p_data->'redirect_uris')<>'array' or jsonb_typeof(p_data->'allowed_scopes')<>'array' then return jsonb_build_object('error','invalid_request'); end if;
  uris:=system_oauth.strings(p_data->'redirect_uris');scope_list:=system_oauth.strings(p_data->'allowed_scopes');
  if cardinality(uris) not between 1 and 10 or exists(select 1 from unnest(uris) u where length(u)>2048 or
   (u !~ '^https://[^/?#[:space:]@]+(/[^#[:space:]]*)?$' and
    not (coalesce((p_data->>'allow_local_http')::boolean,false) and u ~ '^http://(localhost|127\.0\.0\.1)(:[0-9]{1,5})?(/[^#[:space:]]*)?$')))
  or length(coalesce(p_data->>'name','')) not between 1 and 120 or coalesce(p_data->>'client_id','') !~ '^[A-Za-z0-9._-]{8,128}$'
  then return jsonb_build_object('error','invalid_request'); end if;
  if cardinality(scope_list) not between 1 and 4 or not scope_list<@array['profile.read','classes.read','grades.read','assignments.read']::text[] then return jsonb_build_object('error','invalid_scope'); end if;
  if nullif(p_data->>'secret_hash','') is not null and p_data->>'secret_hash' !~ '^[a-f0-9]{64}$' then return jsonb_build_object('error','invalid_request'); end if;
  if nullif(p_data->>'secret_hash','') is null and not coalesce((p_data->>'pkce_required')::boolean,true) then return jsonb_build_object('error','invalid_request'); end if;
  if exists(select 1 from system_oauth.clients where client_id=p_data->>'client_id') then return jsonb_build_object('error','invalid_client'); end if;
  insert into system_oauth.clients(client_id,name,redirect_uris,allowed_scopes,secret_hash,public_client,pkce_required)
  values(p_data->>'client_id',p_data->>'name',uris,scope_list,nullif(p_data->>'secret_hash',''),nullif(p_data->>'secret_hash','') is null,coalesce((p_data->>'pkce_required')::boolean,true));
  perform system_oauth.audit(actor,'OAUTH_CLIENT_REGISTERED',p_data->>'client_id',jsonb_build_object('scopes',scope_list));
  return jsonb_build_object('ok',true,'client_id',p_data->>'client_id');
 end if;
 if p_action='prepare' then
  uid:=(p_data->>'user_id')::uuid;mfa:=(p_data->>'mfa_time')::numeric;
  perform 1 from auth.users where id=uid for share;
  perform 1 from public.profiles where id=uid for share;
  select * into c from system_oauth.clients where client_id=p_data->>'client_id' and active for share;
  if not found then return jsonb_build_object('error','invalid_client'); end if;
  if not coalesce(p_data->>'redirect_uri'=any(c.redirect_uris),false) then return jsonb_build_object('error','invalid_request'); end if;
  if jsonb_typeof(p_data->'scopes')<>'array' then return jsonb_build_object('error','invalid_scope'); end if;
  scope_list:=system_oauth.strings(p_data->'scopes');
  if cardinality(scope_list)=0 or not scope_list<@c.allowed_scopes then return jsonb_build_object('error','invalid_scope'); end if;
  if length(coalesce(p_data->>'state','')) not between 1 and 1024 or coalesce(p_data->>'csrf_hash','') !~ '^[a-f0-9]{64}$'
  or (c.pkce_required and coalesce(p_data->>'code_challenge','') !~ '^[A-Za-z0-9_-]{43}$')
  or (nullif(p_data->>'code_challenge','') is not null and p_data->>'code_challenge' !~ '^[A-Za-z0-9_-]{43}$')
  then return jsonb_build_object('error','invalid_request'); end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text||':'||c.client_id,0));
  err:=system_oauth.browser_error(uid,mfa,(p_data->>'session_id')::uuid);
  if err is not null then
   if err='mfa_required' then perform system_oauth.audit(uid,'OAUTH_MFA_REQUIRED',c.client_id); end if;
   return jsonb_build_object('error',err);
  end if;
  if nullif(p_data->>'session_id','') is null or nullif(p_data->>'request_id','') is null then return jsonb_build_object('error','invalid_request'); end if;
  insert into system_oauth.requests(id,client_id,user_id,session_id,redirect_uri,scopes,state,code_challenge,csrf_hash)
  values((p_data->>'request_id')::uuid,c.client_id,uid,(p_data->>'session_id')::uuid,p_data->>'redirect_uri',scope_list,p_data->>'state',nullif(p_data->>'code_challenge',''),p_data->>'csrf_hash') returning * into r;
  perform system_oauth.audit(uid,'OAUTH_AUTHORIZATION_STARTED',r.id::text,jsonb_build_object('client_id',c.client_id,'scopes',scope_list));
  if exists(select 1 from public.profiles where id=uid and role='manager') then perform system_oauth.audit(uid,'OAUTH_MFA_CONFIRMED',r.id::text); end if;
  return jsonb_build_object('request_id',r.id,'name',c.name,'scopes',r.scopes,'expires_at',r.expires_at);
 end if;
 if p_action='decide' then
  -- Identity -> client -> app/user advisory -> request. Never hold the
  -- advisory lock while waiting on a security writer's identity/client row.
  select * into r from system_oauth.requests where id=(p_data->>'request_id')::uuid;
  if not found then return jsonb_build_object('error','invalid_request'); end if;
  perform 1 from auth.users where id=r.user_id for share;
  perform 1 from public.profiles where id=r.user_id for share;
  select * into c from system_oauth.clients where client_id=r.client_id and active for share;
  if not found then return jsonb_build_object('error','invalid_client'); end if;
  perform pg_advisory_xact_lock(hashtextextended(r.user_id::text||':'||r.client_id,0));
  select * into r from system_oauth.requests where id=(p_data->>'request_id')::uuid for update;
  if not found or r.decided_at is not null or r.expires_at<=clock_timestamp()
  or r.user_id is distinct from (p_data->>'user_id')::uuid or r.session_id is distinct from (p_data->>'session_id')::uuid
  or r.csrf_hash is distinct from p_data->>'csrf_hash' or jsonb_typeof(p_data->'approve')<>'boolean'
  then return jsonb_build_object('error','invalid_request'); end if;
  if not r.scopes<@c.allowed_scopes or not r.redirect_uri=any(c.redirect_uris)
  or (c.pkce_required and r.code_challenge is null) then return jsonb_build_object('error','invalid_request'); end if;
  mfa:=(p_data->>'mfa_time')::numeric;err:=system_oauth.browser_error(r.user_id,mfa,r.session_id);
  if err is not null then return jsonb_build_object('error',err); end if;
  if (p_data->>'approve')::boolean then
   if coalesce(p_data->>'code_hash','') !~ '^[a-f0-9]{64}$' then return jsonb_build_object('error','invalid_request'); end if;
   insert into system_oauth.grants(client_id,user_id,scopes,role_at_issue,mfa_verified_at,mfa_factor_id)
   select r.client_id,r.user_id,r.scopes,p.role,case when p.role='manager' then to_timestamp(mfa::double precision) end,
    case when p.role='manager' then (select factor_id from auth.sessions where id=r.session_id and user_id=r.user_id) end
   from public.profiles p where p.id=r.user_id returning * into g;
   insert into system_oauth.codes(code_hash,grant_id,redirect_uri,code_challenge) values(p_data->>'code_hash',g.id,r.redirect_uri,r.code_challenge);
   perform system_oauth.audit(r.user_id,'OAUTH_CONSENT_APPROVED',g.id::text,jsonb_build_object('client_id',g.client_id,'scopes',g.scopes));
   perform system_oauth.audit(r.user_id,'OAUTH_CODE_ISSUED',g.id::text);
  else
   perform system_oauth.audit(r.user_id,'OAUTH_CONSENT_DENIED',r.id::text,jsonb_build_object('client_id',r.client_id));
  end if;
  update system_oauth.requests set decided_at=clock_timestamp() where id=r.id;
  return jsonb_build_object('redirect_uri',r.redirect_uri,'state',r.state,'approved',(p_data->>'approve')::boolean,'scopes',r.scopes);
 end if;
 if p_action='exchange' then
  select * into code from system_oauth.codes where code_hash=p_data->>'code_hash' for update;
  if not found or code.consumed_at is not null or code.expires_at<=clock_timestamp() then return jsonb_build_object('error','invalid_grant'); end if;
  select * into g from system_oauth.grants where id=code.grant_id for update;
  if code.expires_at<=clock_timestamp() or not system_oauth.grant_live(g) or g.client_id is distinct from p_data->>'client_id'
  or code.redirect_uri is distinct from p_data->>'redirect_uri' or code.code_challenge is distinct from nullif(p_data->>'code_challenge','')
  then return jsonb_build_object('error','invalid_grant'); end if;
  if not exists(select 1 from system_oauth.clients where client_id=g.client_id and code.redirect_uri=any(redirect_uris)) then return jsonb_build_object('error','invalid_grant'); end if;
  if coalesce(p_data->>'access_hash','') !~ '^[a-f0-9]{64}$' or coalesce(p_data->>'refresh_hash','') !~ '^[a-f0-9]{64}$' then return jsonb_build_object('error','invalid_request'); end if;
  update system_oauth.codes set consumed_at=clock_timestamp() where code_hash=code.code_hash;
  insert into system_oauth.access_tokens(token_hash,grant_id,scopes) values(p_data->>'access_hash',g.id,g.scopes);
  insert into system_oauth.refresh_tokens(token_hash,grant_id,scopes,expires_at) values(p_data->>'refresh_hash',g.id,g.scopes,g.created_at+interval '30 days');
  perform system_oauth.audit(g.user_id,'OAUTH_TOKEN_ISSUED',g.id::text,jsonb_build_object('client_id',g.client_id,'scopes',g.scopes));
  return jsonb_build_object('scopes',g.scopes,'expires_in',900);
 end if;
 if p_action='refresh' then
  select * into rt from system_oauth.refresh_tokens where token_hash=p_data->>'refresh_hash' for update;
  if not found then return jsonb_build_object('error','invalid_grant'); end if;
  select * into g from system_oauth.grants where id=rt.grant_id for update;
  if g.client_id is distinct from p_data->>'client_id' then return jsonb_build_object('error','invalid_grant'); end if;
  if rt.consumed_at is not null then
   perform system_oauth.revoke_grant(g.id);
   perform system_oauth.audit(g.user_id,'OAUTH_REFRESH_REUSE',g.id::text,jsonb_build_object('client_id',g.client_id));
   return jsonb_build_object('error','invalid_grant');
  end if;
  if rt.expires_at<=clock_timestamp() or not system_oauth.grant_live(g) then return jsonb_build_object('error','invalid_grant'); end if;
  if coalesce(p_data->>'access_hash','') !~ '^[a-f0-9]{64}$' or coalesce(p_data->>'next_refresh_hash','') !~ '^[a-f0-9]{64}$' then return jsonb_build_object('error','invalid_request'); end if;
  if p_data->'scopes' is null or p_data->'scopes'='null'::jsonb then scope_list:=rt.scopes;
  elsif jsonb_typeof(p_data->'scopes')='array' then scope_list:=system_oauth.strings(p_data->'scopes');
  else return jsonb_build_object('error','invalid_scope'); end if;
  if cardinality(scope_list)=0 or not scope_list<@rt.scopes then return jsonb_build_object('error','invalid_scope'); end if;
  update system_oauth.refresh_tokens set consumed_at=clock_timestamp() where token_hash=rt.token_hash;
  insert into system_oauth.access_tokens(token_hash,grant_id,scopes) values(p_data->>'access_hash',g.id,scope_list);
  insert into system_oauth.refresh_tokens(token_hash,grant_id,scopes,expires_at) values(p_data->>'next_refresh_hash',g.id,scope_list,rt.expires_at);
  perform system_oauth.audit(g.user_id,'OAUTH_TOKEN_REFRESHED',g.id::text,jsonb_build_object('client_id',g.client_id,'scopes',scope_list));
  return jsonb_build_object('scopes',scope_list,'expires_in',900);
 end if;
 if p_action='revoke' then
  select grant_id into gid from system_oauth.access_tokens where token_hash=p_data->>'token_hash';
  if gid is null then select grant_id into gid from system_oauth.refresh_tokens where token_hash=p_data->>'token_hash'; end if;
  select * into g from system_oauth.grants where id=gid and client_id=p_data->>'client_id' for update;
  if found then
   perform system_oauth.revoke_grant(g.id);perform system_oauth.audit(g.user_id,'OAUTH_TOKEN_REVOKED',g.id::text,jsonb_build_object('client_id',g.client_id));
  end if;return jsonb_build_object('ok',true);
 end if;
 if p_action='connections' then
  uid:=(p_data->>'user_id')::uuid;
  select coalesce(jsonb_agg(z order by z.created_at desc),'[]'::jsonb) into answer from (
   select cg.id,cg.client_id,cc.name,cg.scopes,cg.created_at,cg.last_used_at,cg.revoked_at
   from system_oauth.grants cg join system_oauth.clients cc using(client_id)
   where cg.user_id=uid and cg.revoked_at is null and cc.active and system_oauth.grant_live(cg) limit 100
  ) z;return jsonb_build_object('connections',answer);
 end if;
 if p_action='disconnect' then
  actor:=(p_data->>'actor')::uuid;
  select * into g from system_oauth.grants where id=(p_data->>'grant_id')::uuid;
  if not found then return jsonb_build_object('error','access_denied'); end if;
  -- Admin and subject identity rows are sorted within each parent table.
  perform id from auth.users where id in (actor,g.user_id) order by id for share;
  perform id from public.profiles where id in (actor,g.user_id) order by id for share;
  perform 1 from system_oauth.clients where client_id=g.client_id for share;
  perform pg_advisory_xact_lock(hashtextextended(g.user_id::text||':'||g.client_id,0));
  if actor is distinct from g.user_id then
   err:=system_oauth.browser_error(actor,(p_data->>'mfa_time')::numeric,(p_data->>'session_id')::uuid);
   if err is not null then return jsonb_build_object('error',err); end if;
   if not coalesce((p_data->>'admin')::boolean,false) or not exists(select 1 from public.profiles where id=actor and role='manager') then return jsonb_build_object('error','access_denied'); end if;
  end if;
  -- Do not lock the caller-selected grant first: two disconnects selecting
  -- different grants must take the entire app's sorted grant set identically.
  perform system_oauth.revoke_matching(g.user_id,g.client_id);
  perform system_oauth.audit(actor,'OAUTH_DISCONNECTED',g.id::text,jsonb_build_object('client_id',g.client_id,'user_id',g.user_id));
  return jsonb_build_object('ok',true);
 end if;
 return jsonb_build_object('error','invalid_request');
exception when invalid_text_representation or invalid_parameter_value or numeric_value_out_of_range or not_null_violation or unique_violation or check_violation then
 return jsonb_build_object('error','invalid_request');
end $$;

create function public.oauth_api(p_token_hash text,p_resource text,p_filters jsonb default '{}') returns jsonb
language plpgsql security definer set search_path=public,pg_catalog
as $$ declare
 a system_oauth.access_tokens;g system_oauth.grants;required_scope text;claims_before text;
 filter_class uuid;filter_student uuid;filter_subject uuid;page_limit integer;page_offset integer;rows jsonb;
begin
 if current_setting('transaction_isolation')<>'read committed' then raise exception 'OAuth requires READ COMMITTED isolation'; end if;
 select * into a from system_oauth.access_tokens where token_hash=p_token_hash for share;
 if not found or a.expires_at<=clock_timestamp() then return jsonb_build_object('error','invalid_token'); end if;
 select * into g from system_oauth.grants where id=a.grant_id for update;
 if a.expires_at<=clock_timestamp() or not system_oauth.grant_live(g) then return jsonb_build_object('error','invalid_token'); end if;
 required_scope:=case p_resource when 'me' then 'profile.read' when 'classes' then 'classes.read' when 'grades' then 'grades.read' when 'assignments' then 'assignments.read' end;
 if required_scope is null then return jsonb_build_object('error','invalid_request'); end if;
 if not required_scope=any(a.scopes) then return jsonb_build_object('error','insufficient_scope'); end if;
 if p_filters is null or jsonb_typeof(p_filters)<>'object' or exists(select 1 from jsonb_object_keys(p_filters) k where k not in ('class_id','student_id','subject_id','offset','limit')) then return jsonb_build_object('error','invalid_request'); end if;
 filter_class:=nullif(p_filters->>'class_id','')::uuid;filter_student:=nullif(p_filters->>'student_id','')::uuid;filter_subject:=nullif(p_filters->>'subject_id','')::uuid;
 page_limit:=coalesce((p_filters->>'limit')::integer,50);page_offset:=coalesce((p_filters->>'offset')::integer,0);
 if page_limit not between 1 and 100 or page_offset not between 0 and 10000 then return jsonb_build_object('error','invalid_request'); end if;
 claims_before:=coalesce(current_setting('request.jwt.claims',true),'{}');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',g.user_id,'role','authenticated','aal',case when g.role_at_issue='manager' then 'aal2' else 'aal1' end)::text,true);
 if (filter_class is not null and not public.can_read_class(filter_class)) or (filter_student is not null and not public.can_read_student(filter_student)) then
  perform set_config('request.jwt.claims',claims_before,true);return jsonb_build_object('error','access_denied');
 end if;
 if p_resource='me' then
  select jsonb_build_object('id',id,'display_name',full_name) into rows from public.profiles where id=g.user_id;
 elsif p_resource='classes' then
  select coalesce(jsonb_agg(z),'[]') into rows from (
   select c.id,c.title,c.grade_id,c.academic_year from public.classes c
   where public.can_read_class(c.id) and (filter_class is null or c.id=filter_class)
   and (filter_student is null or exists(select 1 from public.class_students cs where cs.class_id=c.id and cs.student_id=filter_student))
   order by c.id limit page_limit offset page_offset
  ) z;
 elsif p_resource='grades' then
  if g.role_at_issue='student' and not coalesce((select report_cards_open from public.school_settings where id=true),false) then
   perform set_config('request.jwt.claims',claims_before,true);return jsonb_build_object('error','access_denied');
  end if;
  select coalesce(jsonb_agg(z),'[]') into rows from (
   select s.id,s.student_id,s.class_id,s.subject_id,s.period,s.continuous_score,s.final_score,s.lesson_score
   from public.scores s
   where (public.is_manager() or (g.role_at_issue='student' and s.student_id=g.user_id) or public.teacher_has_access(s.class_id,s.subject_id))
   and (filter_class is null or s.class_id=filter_class) and (filter_student is null or s.student_id=filter_student)
   and (filter_subject is null or s.subject_id=filter_subject) order by s.id limit page_limit offset page_offset
  ) z;
 elsif p_resource='assignments' then
  select coalesce(jsonb_agg(z),'[]') into rows from (
   select ra.id,ra.title,ra.description,ra.class_id,ra.subject_id,ra.due_at
   from public.assignments ra where (public.is_manager() or (g.role_at_issue='teacher' and ra.teacher_id=g.user_id and public.teacher_has_access(ra.class_id,ra.subject_id)) or (g.role_at_issue='student' and public.student_can_access_assignment(ra.id)))
   and (filter_class is null or ra.class_id=filter_class) and (filter_subject is null or ra.subject_id=filter_subject)
   and (filter_student is null or (g.role_at_issue='student' and filter_student=g.user_id) or
    exists(select 1 from public.class_students cs where cs.class_id=ra.class_id and cs.student_id=filter_student
    and (ra.group_id is null or exists(select 1 from public.student_group_members gm where gm.group_id=ra.group_id and gm.student_id=filter_student))))
   order by ra.id limit page_limit offset page_offset
  ) z;
 end if;
 perform set_config('request.jwt.claims',claims_before,true);
 update system_oauth.grants set last_used_at=clock_timestamp() where id=g.id;
 if p_resource='me' then return rows; end if;
 return jsonb_build_object('rows',rows,'offset',page_offset,'limit',page_limit);
exception when invalid_text_representation or numeric_value_out_of_range then
 if claims_before is not null then perform set_config('request.jwt.claims',claims_before,true); end if;
 return jsonb_build_object('error','invalid_request');
end $$;
revoke execute on all functions in schema system_oauth from public,anon,authenticated,service_role;
revoke execute on function public.oauth_operation(text,jsonb),public.oauth_api(text,text,jsonb) from public,anon,authenticated;
grant execute on function public.oauth_operation(text,jsonb),public.oauth_api(text,text,jsonb) to service_role;
-- Keep refresh tombstones until the family expires so reuse detection survives cleanup.
-- The function accepts no filters and exposes no private row data.
create function public.oauth_cleanup() returns jsonb
language plpgsql security definer set search_path=public,pg_catalog
as $$ declare n_requests integer;n_codes integer;n_access integer;n_refresh integer;n_grants integer;n_rates integer;begin
 perform pg_advisory_xact_lock(20261007,1);
 -- Expired credential leaves precede grants; request rows follow grants,
 -- matching security revocation and avoiding request/grant lock inversion.
 delete from system_oauth.codes where expires_at<=clock_timestamp();get diagnostics n_codes=row_count;
 delete from system_oauth.access_tokens where expires_at<=clock_timestamp();get diagnostics n_access=row_count;
 delete from system_oauth.refresh_tokens where expires_at<clock_timestamp()-interval '1 day';get diagnostics n_refresh=row_count;
 with expired as (select id from system_oauth.grants
  where created_at<clock_timestamp()-interval '31 days' or revoked_at<clock_timestamp()-interval '31 days'
  order by id for update)
 delete from system_oauth.grants g using expired e where g.id=e.id;get diagnostics n_grants=row_count;
 delete from system_oauth.requests where expires_at<=clock_timestamp();get diagnostics n_requests=row_count;
 delete from system_oauth.rate_limits where started_at<clock_timestamp()-interval '1 hour';get diagnostics n_rates=row_count;
 return jsonb_build_object('requests',n_requests,'codes',n_codes,'access_tokens',n_access,'refresh_tokens',n_refresh,'grants',n_grants,'rate_keys',n_rates);
end $$;
revoke execute on function public.oauth_cleanup() from public,anon,authenticated;
grant execute on function public.oauth_cleanup() to service_role;
do $$ begin
 if exists(select 1 from pg_extension where extname='pg_cron') then
  perform cron.schedule('system-oauth-cleanup','17 * * * *','select public.oauth_cleanup()');
 end if;
end $$;
notify pgrst,'reload schema';

-- Source: supabase/migrations/20261009_manager_session_guard.sql
-- SHA-256: 3304b22a56a6d3cea271a9370f2fe3e8a5a4a5190251bc90d686d94730d94a81
-- Additional service-only boundary for existing manager Edge Functions.
-- Run after the v7 profile migrations. The original Login/MFA implementation
-- remains Supabase Auth; no parallel identity or factor records are created.

create or replace function public.assert_manager_session(p_user uuid,p_session uuid) returns boolean
language plpgsql volatile security definer set search_path=public,pg_catalog
as $manager_session$
declare current_session auth.sessions;
begin
  -- Only the Edge Function can supply these IDs after validating the exact JWT
  -- through native Auth and checking its subject/session/issuer/audience/AAL.
  if p_user is null or p_session is null or not exists(
    select 1 from public.profiles p join auth.users u on u.id=p.id
    where p.id=p_user and p.role='manager' and p.active
      and (nullif(to_jsonb(u)->>'banned_until','') is null or (to_jsonb(u)->>'banned_until')::timestamptz<=clock_timestamp())
      and nullif(to_jsonb(u)->>'deleted_at','') is null
  ) then raise exception 'MFA_REQUIRED'; end if;
  -- Do not wait on a session while another native Auth flow can hold the
  -- opposite identity lock. A busy session fails closed and can be retried.
  select * into current_session from auth.sessions where id=p_session and user_id=p_user for share nowait;
  if not found or (current_session.not_after is not null and current_session.not_after<=clock_timestamp())
    or current_session.aal is distinct from 'aal2' or not exists(
      select 1 from auth.mfa_factors f where f.id=current_session.factor_id and f.user_id=p_user
        and f.status='verified' and f.factor_type='totp'
    ) then raise exception 'MFA_REQUIRED'; end if;
  -- Initial manager password change must remain possible after real TOTP.
  -- Ordinary admin operations separately require must_change_password=false.
  -- The connector's additional ten-minute step-up policy remains independent.
  return true;
exception when lock_not_available then raise exception 'MFA_REQUIRED';
end $manager_session$;
revoke execute on function public.assert_manager_session(uuid,uuid) from public,anon,authenticated;
grant execute on function public.assert_manager_session(uuid,uuid) to service_role;
notify pgrst,'reload schema';

-- Allow trusted Edge service requests to execute the existing pre-request guard.
-- Keep the guard itself and its restrictions on native OAuth JWTs unchanged.
grant execute on function public.oauth_postgrest_guard() to service_role;
notify pgrst,'reload schema';
commit;

-- Success output contains status only, never identity details or secrets.
select
  (select count(*) from pg_tables where schemaname='system_oauth') as oauth_tables,
  (select count(*) from pg_tables where schemaname='system_oauth' and rowsecurity) as oauth_rls_tables,
  has_function_privilege('service_role','public.oauth_postgrest_guard()','EXECUTE') as service_guard_allowed,
  to_regprocedure('public.assert_manager_session(uuid,uuid)') is not null as manager_session_guard_ready;
