(() => {
'use strict';
const c=window.SystemCore,V=window.SchoolV7,{state:s,$,esc:e}=c;
V.routes.appointments=async()=>{
let page=0,appointmentPage=0;
V.page('ملاقات‌ها','رزرو ملاقات با مدیر یا دبیر',`<div class="card">${V.toolbar(V.staff()?V.button('newSlot','زمان ملاقات جدید'):'')}<h3>زمان‌های ملاقات</h3><div id="slotList"></div><h3>درخواست‌های ملاقات</h3><div id="appointmentList"></div></div>`);
async function draw(){const {data:slots,error,count}=await s.sb.from('appointment_slots').select('*',{count:'exact'}).order('date').order('start_time').gte('date',V.today()).range(page*50,page*50+49);if(error)throw error;
$('#slotList').innerHTML=c.table(['مسئول','تاریخ','ساعت','محل','ظرفیت','عملیات'],slots.map(t=>`<tr><td>${e(c.userName(t.staff_id))}</td><td>${V.date(t.date+'T12:00:00Z')}</td><td>${e(t.start_time.slice(0,5))} تا ${e(t.end_time.slice(0,5))}</td><td>${e(t.location)}</td><td>${t.capacity}</td><td>${s.profile.role==='student'&&t.active?`<button class="btn btn-primary reserve-slot" data-id="${t.id}">رزرو</button>`:''}${V.manager()||t.staff_id===s.profile.id?`<button class="btn btn-ghost slot-active" data-id="${t.id}">${t.active?'بستن رزرو':'باز کردن رزرو'}</button>`:''}</td></tr>`))+V.pager(page,count||0);
V.bind('.slot-active',async b=>{const t=slots.find(x=>x.id===b.dataset.id);await V.query(s.sb.from('appointment_slots').update({active:!t.active}).eq('id',t.id));await draw();});
V.bind('.reserve-slot',b=>{c.modal('درخواست ملاقات',`<div class="form-grid">${V.field('apSubject','موضوع ملاقات')}<label class="wide"><span>توضیح</span><textarea id="apDescription"></textarea></label></div>`,async()=>{await V.rpc('book_appointment',{p_slot:b.dataset.id,p_subject:$('#apSubject').value.trim(),p_description:$('#apDescription').value.trim()});c.toast('درخواست ملاقات ثبت شد.');await draw();},'ارسال درخواست');});
$('#prevPage').disabled=page===0;$('#nextPage').disabled=(page+1)*50>=(count||0);V.bind('#prevPage',async()=>{page--;await draw();});V.bind('#nextPage',async()=>{page++;await draw();});
const {data:appointments,error:appointmentError,count:appointmentCount}=await s.sb.from('appointments').select('*,appointment_slots(*)',{count:'exact'}).order('created_at',{ascending:false}).range(appointmentPage*50,appointmentPage*50+49);if(appointmentError)throw appointmentError;
$('#appointmentList').innerHTML=c.table(['موضوع','درخواست‌کننده','زمان','وضعیت','عملیات'],appointments.map(a=>{const t=a.appointment_slots,owner=V.manager()||t?.staff_id===s.profile.id;return `<tr><td>${e(a.subject)}<small class="v7-block">${e(a.description)}</small></td><td>${e(c.userName(a.requester_id))}</td><td>${t?V.date(t.date+'T12:00:00Z')+' · '+e(t.start_time.slice(0,5)):'—'}</td><td>${V.badge(a.status)}</td><td>${owner?['approved','rejected','completed'].map(st=>`<button class="btn btn-ghost appointment-state" data-id="${a.id}" data-status="${st}">${e(V.label(st))}</button>`).join(''):''}${a.status!=='completed'?`<button class="btn btn-ghost appointment-state" data-id="${a.id}" data-status="cancelled">لغو</button>`:''}</td></tr>`;}));
$('#appointmentList').insertAdjacentHTML('beforeend',V.pager(appointmentPage,appointmentCount||0,50,'appointment'));$('#appointmentprevPage').disabled=appointmentPage===0;$('#appointmentnextPage').disabled=(appointmentPage+1)*50>=(appointmentCount||0);V.bind('#appointmentprevPage',async()=>{appointmentPage--;await draw();});V.bind('#appointmentnextPage',async()=>{appointmentPage++;await draw();});
V.bind('.appointment-state',async b=>{await V.rpc('set_appointment_status',{p_appointment:b.dataset.id,p_status:b.dataset.status});await draw();});}
V.bind('#newSlot',()=>{c.modal('زمان قابل رزرو',`<div class="form-grid">${V.select('slStaff','مسئول',V.manager()?V.personOptions().filter(p=>s.profiles.find(u=>u.id===p.id)?.role!=='student'):[{id:s.profile.id,title:s.profile.full_name}])}${V.dateField('slDate','تاریخ')}${V.field('slStart','شروع','time','14:00')}${V.field('slEnd','پایان','time','14:30')}${V.field('slLocation','محل','text','دفتر مدرسه',false)}${V.field('slCapacity','ظرفیت','number',1)}</div>`,async()=>{await V.query(s.sb.from('appointment_slots').insert({staff_id:V.value('slStaff'),date:V.gregorian(V.value('slDate')),start_time:V.value('slStart'),end_time:V.value('slEnd'),location:$('#slLocation').value.trim(),capacity:V.number('slCapacity')}));c.toast('زمان ملاقات ثبت شد.');await draw();});});await draw();};
})();
