(() => {
'use strict';
const c=window.SystemCore,V=window.SchoolV7,{state:s,$,esc:e}=c;
V.routes.behavior=async()=>{
let page=0;const categories=await V.query(s.sb.from('behavior_categories').select('*').order('title'));
V.page('رفتار و تشویق','ثبت رویدادهای مثبت، منفی و خنثی',`<div class="card">${V.toolbar((V.staff()?V.button('newBehavior','رویداد جدید'):'')+(V.manager()?V.button('newBehaviorCategory','دسته جدید','btn-ghost'):''))}${V.select('behaviorClass','کلاس',V.classOptions(),'',true)}<div id="behaviorList"></div></div>`);
async function draw(){let q=s.sb.from('behavior_events').select('*',{count:'exact'}).order('event_date',{ascending:false}).range(page*50,page*50+49);if(V.value('behaviorClass'))q=q.eq('class_id',V.value('behaviorClass'));const {data,error,count}=await q;if(error)throw error;
$('#behaviorList').innerHTML=c.table(['تاریخ','دانش‌آموز','دسته','عنوان','نوع','امتیاز'],(data||[]).map(r=>`<tr><td>${V.date(r.event_date+'T12:00:00Z')}</td><td>${e(c.userName(r.student_id))}</td><td>${e(categories.find(x=>x.id===r.category)?.title)}</td><td>${e(r.title)}<small class="v7-block">${e(r.description)}</small></td><td>${V.badge(r.event_type)}</td><td>${r.points>0?'+':''}${r.points}</td></tr>`))+V.pager(page,count||0);
$('#prevPage').disabled=page===0;$('#nextPage').disabled=(page+1)*50>=(count||0);V.bind('#prevPage',async()=>{page--;await draw();});V.bind('#nextPage',async()=>{page++;await draw();});}
$('#behaviorClass').onchange=()=>{page=0;draw().catch(err=>c.toast(c.errText(err),true));};
V.bind('#newBehavior',()=>{
c.modal('ثبت رفتار',`<div class="form-grid">${V.select('bClass','کلاس',V.classOptions())}${V.select('bStudent','دانش‌آموز',[])}${V.select('bSubject','درس (اختیاری)',[],'',true)}${V.dateField('bDate','تاریخ')}${V.select('bCategory','دسته',categories.filter(x=>x.active))}${V.field('bTitle','عنوان')}${V.field('bPoints','امتیاز','number',categories[0]?.default_points||0)}<label class="wide"><span>توضیح</span><textarea id="bDescription"></textarea></label></div>`,async()=>{const category=categories.find(x=>x.id===V.value('bCategory'));await V.query(s.sb.from('behavior_events').insert({student_id:V.value('bStudent'),class_id:V.value('bClass'),subject_id:V.value('bSubject')||null,event_date:V.gregorian(V.value('bDate')),category:category.id,event_type:category.event_type,title:$('#bTitle').value.trim(),description:$('#bDescription').value.trim(),points:V.number('bPoints'),recorded_by:s.profile.id}));c.toast('رویداد ذخیره شد.');await draw();});
const students=()=>{$('#bStudent').innerHTML=V.students(V.value('bClass')).map(x=>`<option value="${x.id}">${e(x.full_name)}</option>`).join('');$('#bSubject').innerHTML='<option value="">بدون درس</option>'+V.subjects(V.value('bClass')).map(x=>`<option value="${x.id}">${e(x.title)}</option>`).join('');};$('#bClass').onchange=students;students();$('#bCategory').onchange=()=>{$('#bPoints').value=categories.find(x=>x.id===V.value('bCategory'))?.default_points||0;};});
V.bind('#newBehaviorCategory',()=>{c.modal('دسته رفتار جدید',`<div class="form-grid">${V.field('bcTitle','عنوان')}${V.select('bcType','نوع',V.options({positive:'مثبت',negative:'منفی',neutral:'خنثی'}))}${V.field('bcPoints','امتیاز پیش‌فرض','number',0)}</div>`,async()=>{await V.query(s.sb.from('behavior_categories').insert({title:$('#bcTitle').value.trim(),event_type:V.value('bcType'),default_points:V.number('bcPoints')}));await c.navigate('behavior');});});await draw();};
})();
