(() => {
'use strict';
const c=window.SystemCore,V=window.SchoolV7,{state:s,$,esc:e}=c;
V.routes.calendar=async()=>{
const anchor=V.calendarAnchor||V.shamsi(),[year,month]=anchor.split('/').map(Number),start=V.gregorian(`${year}/${month}/1`),next=V.gregorian(`${month===12?year+1:year}/${month===12?1:month+1}/1`);
const events=await V.rpc('get_school_calendar',{p_from:start+'T00:00:00+03:30',p_to:next+'T00:00:00+03:30'}),first=new Date(start+'T12:00:00Z'),offset=(first.getUTCDay()+1)%7,dates=[];
for(let day=new Date(first);day.toISOString().slice(0,10)<next;day.setUTCDate(day.getUTCDate()+1))dates.push(new Date(day));
const eventsFor=day=>events.filter(x=>{const date=day.toISOString().slice(0,10);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(x.start_at))<=date&&new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tehran',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(x.end_at))>=date;});
V.page('تقویم آموزشی','رویدادها، تکالیف، آزمون‌ها، فوق‌برنامه و ملاقات‌های تأییدشده',`<div class="card"><div class="v7-toolbar no-print">${V.button('calendarPrevious','ماه قبل','btn-ghost')}<strong>${new Intl.DateTimeFormat('fa-IR-u-ca-persian',{month:'long',year:'numeric',timeZone:'Asia/Tehran'}).format(first)}</strong>${V.button('calendarNext','ماه بعد','btn-ghost')}${V.manager()?V.button('newCalendarEvent','رویداد جدید'):''}</div><div class="v7-calendar"><div class="v7-calendar-week">${V.days.map(x=>`<span>${x}</span>`).join('')}</div><div class="v7-calendar-days">${Array(offset).fill('<div class="v7-calendar-blank"></div>').join('')}${dates.map(day=>`<div class="v7-calendar-day"><b>${V.shamsi(day).split('/')[2]}</b>${eventsFor(day).map(x=>`<button class="v7-calendar-event" data-id="${x.id}"><span>${e(x.title)}</span><small>${e(V.label(x.type))}</small></button>`).join('')}</div>`).join('')}</div></div><div class="v7-calendar-agenda">${c.table(['عنوان','نوع','شروع','پایان'],events.map(x=>`<tr><td>${e(x.title)}</td><td>${e(V.label(x.type))}</td><td>${V.datetime(x.start_at)}</td><td>${V.datetime(x.end_at)}</td></tr>`))}</div></div>`);
const move=async delta=>{let m=month+delta,y=year;if(m===0){m=12;y--;}if(m===13){m=1;y++;}V.calendarAnchor=`${y}/${m}/1`;await c.navigate('calendar');};V.bind('#calendarPrevious',()=>move(-1));V.bind('#calendarNext',()=>move(1));
V.bind('.v7-calendar-event',b=>{const x=events.find(x=>x.id===b.dataset.id);c.modal(x.title,`<p>${e(V.label(x.type))}</p><p>${V.datetime(x.start_at)} تا ${V.datetime(x.end_at)}</p>`,async()=>{await c.navigate(x.route);},'نمایش بخش مرتبط');});
V.bind('#newCalendarEvent',()=>{c.modal('رویداد آموزشی',`<div class="form-grid">${V.field('ceTitle','عنوان')}${V.select('ceType','نوع رویداد',V.options({exam:'امتحان',holiday:'تعطیلی',parents_meeting:'جلسه اولیا',trip:'اردو',competition:'مسابقه',cultural:'فرهنگی',school_meeting:'جلسه مدرسه',deadline:'مهلت مهم',other:'سایر'}))}${V.dateField('ceStart','شروع',new Date(),true)}${V.dateField('ceEnd','پایان',new Date(Date.now()+3600000),true)}${V.audience()}<label><span>تمام روز</span><input type="checkbox" id="ceAllDay"></label><label class="wide"><span>توضیح</span><textarea id="ceDescription"></textarea></label></div>`,async()=>{await V.query(s.sb.from('calendar_events').insert({title:$('#ceTitle').value.trim(),description:$('#ceDescription').value.trim(),event_type:V.value('ceType'),start_at:V.stamp('ceStart'),end_at:V.stamp('ceEnd'),all_day:$('#ceAllDay').checked,...V.audienceValue(),created_by:s.profile.id}));c.toast('رویداد ثبت شد.');await c.navigate('calendar');});});};
})();
