(() => {
"use strict";
const V=window.SchoolV8;let cursor=new Date();
function range(d){return {start:new Date(d.getFullYear(),d.getMonth(),1),end:new Date(d.getFullYear(),d.getMonth()+1,1)}}
async function render(){
  const A=V.app(),role=V.state().profile.role;A.setPage("تقویم آموزشی","رویدادها، تکالیف، آزمون‌ها، فوق‌برنامه و ملاقات‌ها");const {start,end}=range(cursor);const items=await V.rpc("calendar_feed_v8",{p_start:start.toISOString(),p_end:end.toISOString()})||[];const title=new Intl.DateTimeFormat("fa-IR-u-ca-persian",{month:"long",year:"numeric"}).format(cursor);const grouped=new Map();items.forEach(x=>{const key=new Date(x.starts_at).toISOString().slice(0,10);if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(x)});
  document.querySelector("#content").innerHTML=`<div class="panel-head page-actions"><div><h3>${title}</h3><p class="muted">تاریخ‌ها در رابط شمسی و در دیتابیس استاندارد ذخیره می‌شوند.</p></div><div class="actions"><button class="btn btn-ghost" id="calPrev">ماه قبل</button><button class="btn btn-ghost" id="calToday">امروز</button><button class="btn btn-ghost" id="calNext">ماه بعد</button>${role==="manager"?'<button class="btn btn-primary" id="addCalendarEvent">+ رویداد</button>':""}</div></div><section class="card calendar-feed">${items.length?[...grouped.entries()].map(([date,list])=>`<div class="calendar-day-group"><div class="calendar-day-title">${V.dateOnly(date)}</div><div>${list.map(x=>`<button class="calendar-feed-item" data-route="${V.escape(x.link||"calendar")}"><span class="calendar-source ${x.source}"></span><span><strong>${V.escape(x.title)}</strong><small>${V.dateTime(x.starts_at)}${x.ends_at&&x.ends_at!==x.starts_at?" تا "+V.dateTime(x.ends_at):""}</small></span></button>`).join("")}</div></div>`).join(""):'<div class="empty">در این ماه رویدادی ثبت نشده است.</div>'}</section>`;
  document.querySelector("#calPrev").onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);render()};document.querySelector("#calNext").onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);render()};document.querySelector("#calToday").onclick=()=>{cursor=new Date();render()};document.querySelectorAll(".calendar-feed-item").forEach(b=>b.onclick=()=>V.route(b.dataset.route));if(document.querySelector("#addCalendarEvent"))document.querySelector("#addCalendarEvent").onclick=eventModal;
}
function eventModal(){
  const A=V.app(),s=V.state();A.modal("رویداد جدید",`<div class="form-grid"><label class="wide"><span>عنوان</span><input id="evTitle"></label><label><span>نوع</span><select id="evType">${Object.entries(V.eventLabels).map(([k,v])=>`<option value="${k}">${v}</option>`).join("")}</select></label><label><span>مخاطب</span><select id="evTarget"><option value="all">همه</option><option value="role">یک نقش</option><option value="grade">یک پایه</option><option value="class">یک کلاس</option><option value="user">یک کاربر</option></select></label><label><span>شروع</span><input id="evStart" type="datetime-local"></label><label><span>پایان</span><input id="evEnd" type="datetime-local"></label><label><span>نقش</span><select id="evRole"><option value="teacher">دبیر</option><option value="student">دانش‌آموز</option></select></label><label><span>پایه</span><select id="evGrade"><option value="">-</option>${s.grades.map(x=>`<option value="${x.id}">${V.escape(x.title)}</option>`).join("")}</select></label><label><span>کلاس</span><select id="evClass"><option value="">-</option>${s.classes.map(x=>`<option value="${x.id}">${V.escape(V.classLabel(x.id))}</option>`).join("")}</select></label><label><span>کاربر</span><select id="evUser"><option value="">-</option>${s.profiles.filter(x=>x.role!=="manager").map(x=>`<option value="${x.id}">${V.escape(x.full_name)}</option>`).join("")}</select></label><label class="wide"><span>توضیحات</span><textarea id="evDescription"></textarea></label></div>`,async()=>{const target=document.querySelector("#evTarget").value,start=document.querySelector("#evStart").value;if(!start)throw new Error("زمان شروع الزامی است.");const payload={title:document.querySelector("#evTitle").value.trim(),description:document.querySelector("#evDescription").value.trim()||null,event_type:document.querySelector("#evType").value,start_at:new Date(start).toISOString(),end_at:document.querySelector("#evEnd").value?new Date(document.querySelector("#evEnd").value).toISOString():null,target_type:target,created_by:s.profile.id,target_role:target==="role"?document.querySelector("#evRole").value:null,target_grade_id:target==="grade"?document.querySelector("#evGrade").value:null,target_class_id:target==="class"?document.querySelector("#evClass").value:null,target_user_id:target==="user"?document.querySelector("#evUser").value:null};if(!payload.title)throw new Error("عنوان الزامی است.");const {error}=await V.sb().from("calendar_events").insert(payload);if(error)throw error;V.success("رویداد ثبت شد.");render()},"ثبت رویداد");
}
V.registerRoute("calendar",render);
})();
