(() => {
'use strict';
const c=window.SystemCore,V=window.SchoolV7,{state:s,$,esc:e}=c;
const categories={support:'تقویتی',sports:'ورزشی',art:'هنری',cultural:'فرهنگی',language:'زبان',olympiad:'المپیاد',laboratory:'آزمایشگاه',other:'سایر'};
V.routes.extracurricular=async()=>{
let page=0;
V.page('کلاس‌های فوق‌برنامه','ثبت‌نام، ظرفیت و مدیریت جلسات',`<div class="card">${V.toolbar(V.staff()?V.button('newExtra','کلاس جدید'):'')}<div id="extraList"></div></div>`);
async function draw(){const {data,error,count}=await s.sb.from('extracurricular_classes').select('*',{count:'exact'}).order('starts_at').range(page*50,page*50+49);if(error)throw error;
const counts=await V.rpc('extracurricular_counts');$('#extraList').innerHTML=c.table(['عنوان','مسئول','زمان','مهلت ثبت‌نام','ظرفیت','عملیات'],data.map(x=>`<tr><td>${e(x.title)}<small class="v7-block">${e(categories[x.category]||x.category)} · ${e(x.location)}</small></td><td>${e(c.userName(x.teacher_id))}</td><td>${V.datetime(x.starts_at)}</td><td>${V.datetime(x.registration_end)}</td><td>${counts[x.id]||0} / ${x.capacity}</td><td>${s.profile.role==='student'?`<button class="btn btn-primary register-extra" data-id="${x.id}">ثبت‌نام</button>`:''}<button class="btn btn-ghost extra-detail" data-id="${x.id}">جلسات و اعضا</button>${V.manager()||x.teacher_id===s.profile.id?`<button class="btn btn-ghost extra-edit" data-id="${x.id}">ویرایش</button>`:''}</td></tr>`))+V.pager(page,count||0);
V.bind('.register-extra',async b=>{await V.rpc('register_extracurricular',{p_class:b.dataset.id});c.toast('درخواست ثبت‌نام ثبت شد.');await draw();});V.bind('.extra-edit',b=>extraModal(data.find(x=>x.id===b.dataset.id)));
V.bind('.extra-detail',async b=>{V.extraClass=data.find(x=>x.id===b.dataset.id);await c.navigate('extracurricular-detail');});$('#prevPage').disabled=page===0;$('#nextPage').disabled=(page+1)*50>=(count||0);V.bind('#prevPage',async()=>{page--;await draw();});V.bind('#nextPage',async()=>{page++;await draw();});}
V.bind('#newExtra',()=>extraModal());await draw();};
function extraModal(x=null){
c.modal(x?'ویرایش فوق‌برنامه':'کلاس فوق‌برنامه جدید',`<div class="form-grid">${V.field('ecTitle','عنوان','text',x?.title||'')}${V.select('ecCategory','نوع کلاس',V.options(categories),x?.category)}${V.select('ecTeacher','مسئول',V.manager()?V.personOptions('teacher'):[{id:s.profile.id,title:s.profile.full_name}],x?.teacher_id)}${V.field('ecCapacity','ظرفیت','number',x?.capacity||20)}${V.field('ecLocation','محل','text',x?.location||'',false)}${V.dateField('ecStart','شروع کلاس',x?.starts_at||new Date(Date.now()+7*86400000),true)}${V.dateField('ecEnd','پایان کلاس',x?.ends_at||new Date(Date.now()+7*86400000+3600000),true)}${V.dateField('ecRegStart','شروع ثبت‌نام',x?.registration_start||new Date(),true)}${V.dateField('ecRegEnd','پایان ثبت‌نام',x?.registration_end||new Date(Date.now()+6*86400000),true)}<label class="wide"><span>توضیح</span><textarea id="ecDescription">${e(x?.description||'')}</textarea></label><label><span>فعال</span><input id="ecActive" type="checkbox" ${x?.active===false?'':'checked'}></label></div>`,async()=>{
const p={title:$('#ecTitle').value.trim(),category:V.value('ecCategory'),teacher_id:V.value('ecTeacher'),capacity:V.number('ecCapacity'),location:$('#ecLocation').value.trim(),starts_at:V.stamp('ecStart'),ends_at:V.stamp('ecEnd'),registration_start:V.stamp('ecRegStart'),registration_end:V.stamp('ecRegEnd'),description:$('#ecDescription').value.trim(),active:$('#ecActive').checked};
await V.query(x?s.sb.from('extracurricular_classes').update(p).eq('id',x.id):s.sb.from('extracurricular_classes').insert(p));c.toast('کلاس ذخیره شد.');await c.navigate('extracurricular');});}
V.routes['extracurricular-detail']=async()=>{
const x=V.extraClass;if(!x)return c.navigate('extracurricular');const owner=V.manager()||x.teacher_id===s.profile.id;
let sessionPage=0,enrollmentPage=0;
V.page(x.title,'جلسات و وضعیت ثبت‌نام',`<div class="card"><p>${e(x.description)}</p>${V.toolbar(V.button('backExtras','فوق‌برنامه‌ها','btn-ghost')+(owner?V.button('newExtraSession','جلسه جدید'):''))}<h3>جلسات</h3><div id="extraSessions"></div><h3>ثبت‌نام‌ها</h3><div id="extraEnrollments"></div></div>`);
async function drawSessions(){const {data:sessions,error,count}=await s.sb.from('extracurricular_sessions').select('*',{count:'exact'}).eq('class_id',x.id).order('start_at').range(sessionPage*50,sessionPage*50+49);if(error)throw error;
$('#extraSessions').innerHTML=c.table(['عنوان','شروع','پایان','محل'],sessions.map(t=>`<tr><td>${e(t.title||x.title)}</td><td>${V.datetime(t.start_at)}</td><td>${V.datetime(t.end_at)}</td><td>${e(t.location||x.location)}</td></tr>`))+V.pager(sessionPage,count||0,50,'sessions');
$('#sessionsprevPage').disabled=sessionPage===0;$('#sessionsnextPage').disabled=(sessionPage+1)*50>=(count||0);V.bind('#sessionsprevPage',async()=>{sessionPage--;await drawSessions();});V.bind('#sessionsnextPage',async()=>{sessionPage++;await drawSessions();});}
async function drawEnrollments(){const {data:enrollments,error,count}=await s.sb.from('extracurricular_enrollments').select('*',{count:'exact'}).eq('class_id',x.id).order('registered_at').range(enrollmentPage*50,enrollmentPage*50+49);if(error)throw error;
$('#extraEnrollments').innerHTML=c.table(['دانش‌آموز','وضعیت','عملیات'],enrollments.map(r=>`<tr><td>${e(c.userName(r.student_id))}</td><td>${V.badge(r.status)}</td><td>${owner?`<button class="btn btn-primary extra-state" data-id="${r.id}" data-status="approved">تأیید</button><button class="btn btn-ghost extra-state" data-id="${r.id}" data-status="rejected">رد</button>`:''}${owner||r.student_id===s.profile.id?`<button class="btn btn-ghost extra-state" data-id="${r.id}" data-status="cancelled">لغو</button>`:''}</td></tr>`))+V.pager(enrollmentPage,count||0,50,'enrollment');
$('#enrollmentprevPage').disabled=enrollmentPage===0;$('#enrollmentnextPage').disabled=(enrollmentPage+1)*50>=(count||0);V.bind('#enrollmentprevPage',async()=>{enrollmentPage--;await drawEnrollments();});V.bind('#enrollmentnextPage',async()=>{enrollmentPage++;await drawEnrollments();});
V.bind('.extra-state',async b=>{await V.rpc('set_extracurricular_status',{p_enrollment:b.dataset.id,p_status:b.dataset.status});await drawEnrollments();});}
V.bind('#backExtras',()=>c.navigate('extracurricular'));V.bind('#newExtraSession',()=>{
c.modal('جلسه فوق‌برنامه',`<div class="form-grid">${V.field('esTitle','عنوان','text',x.title)}${V.field('esLocation','محل','text',x.location||'',false)}${V.dateField('esStart','شروع',new Date(),true)}${V.dateField('esEnd','پایان',new Date(Date.now()+3600000),true)}</div>`,async()=>{await V.query(s.sb.from('extracurricular_sessions').insert({class_id:x.id,title:$('#esTitle').value.trim(),location:$('#esLocation').value.trim(),start_at:V.stamp('esStart'),end_at:V.stamp('esEnd')}));sessionPage=0;await drawSessions();});});await Promise.all([drawSessions(),drawEnrollments()]);};
})();
