(() => {
'use strict';
const c=window.SystemCore,V=window.SchoolV7,{state:s,$,esc:e}=c;
V.routes.polls=async()=>{
let page=0;V.page('نظرسنجی و رأی‌گیری','هر کاربر یک رأی؛ حفظ هویت در نظرسنجی ناشناس',`<div class="card">${V.toolbar(V.manager()?V.button('newPoll','نظرسنجی جدید'):'')}<div id="pollList"></div></div>`);
async function draw(){const {data,error,count}=await s.sb.from('polls').select('*',{count:'exact'}).order('starts_at',{ascending:false}).range(page*50,page*50+49);if(error)throw error;
$('#pollList').innerHTML=c.table(['عنوان','مهلت','نوع','عملیات'],(data||[]).map(p=>`<tr><td>${e(p.title)}</td><td>${V.datetime(p.ends_at)}</td><td>${p.anonymous?'ناشناس':'با نام'}</td><td><button class="btn btn-primary poll-vote" data-id="${p.id}">رأی دادن</button>${p.show_results||V.manager()?`<button class="btn btn-ghost poll-result" data-id="${p.id}">نتایج</button>`:''}${V.manager()?`<button class="btn btn-ghost poll-show" data-id="${p.id}">${p.show_results?'بستن نتایج':'نمایش نتایج'}</button>`:''}</td></tr>`))+V.pager(page,count||0);
V.bind('.poll-vote',async b=>{const p=data.find(x=>x.id===b.dataset.id),options=await V.query(s.sb.from('poll_options').select('*').eq('poll_id',p.id).order('sort_order'));
c.modal(p.title,`<p>${e(p.description)}</p>${options.map(o=>`<label class="v7-choice"><input type="radio" name="pollOption" value="${o.id}" required><span>${e(o.option_text)}</span></label>`).join('')}`,async()=>{const option=$('input[name=pollOption]:checked')?.value;if(!option)throw new Error('گزینه موردنظر را انتخاب کنید.');await V.rpc('vote_school_poll',{p_poll:p.id,p_option:option});c.toast('رأی شما ثبت شد.');},'ثبت رأی');});
V.bind('.poll-show',async b=>{const p=data.find(x=>x.id===b.dataset.id);await V.query(s.sb.from('polls').update({show_results:!p.show_results}).eq('id',p.id));await draw();});
V.bind('.poll-result',async b=>{const p=data.find(x=>x.id===b.dataset.id),r=await V.rpc('school_poll_results',{p_poll:p.id});
c.modal('نتایج '+p.title,`<p>مشارکت‌کنندگان: ${r.participants}</p>${r.options.map(o=>`<div class="v7-poll-result"><strong>${e(o.option_text)}</strong><span>${o.votes} رأی · ${o.percent}٪</span><progress max="100" value="${o.percent}"></progress></div>`).join('')}${!r.anonymous&&r.voters.length?c.table(['کاربر','گزینه'],r.voters.map(v=>`<tr><td>${e(v.name)}</td><td>${e(r.options.find(o=>o.id===v.option_id)?.option_text)}</td></tr>`)):''}`,async()=>{},'بستن');});
$('#prevPage').disabled=page===0;$('#nextPage').disabled=(page+1)*50>=(count||0);V.bind('#prevPage',async()=>{page--;await draw();});V.bind('#nextPage',async()=>{page++;await draw();});}
V.bind('#newPoll',()=>{c.modal('نظرسنجی جدید',`<div class="form-grid">${V.field('pTitle','عنوان')}<label><span>توضیح</span><textarea id="pDescription"></textarea></label>${V.audience()}${V.dateField('pStart','شروع',new Date(),true)}${V.dateField('pEnd','پایان',new Date(Date.now()+7*86400000),true)}<label><span>ناشناس</span><input type="checkbox" id="pAnonymous" checked></label><label><span>نمایش نتیجه</span><input type="checkbox" id="pShow"></label><label class="wide"><span>گزینه‌ها (هر گزینه در یک خط)</span><textarea id="pOptions" required></textarea></label></div>`,async()=>{const options=$('#pOptions').value.split('\n').map(x=>x.trim()).filter(Boolean);if(options.length<2)throw new Error('حداقل دو گزینه وارد کنید.');
await V.rpc('create_school_poll',{p_poll:{title:$('#pTitle').value.trim(),description:$('#pDescription').value.trim(),...V.audienceValue(),starts_at:V.stamp('pStart'),ends_at:V.stamp('pEnd'),anonymous:$('#pAnonymous').checked,show_results:$('#pShow').checked},p_options:options});c.toast('نظرسنجی ساخته شد.');await draw();});});await draw();};
})();
