(() => {
'use strict';
const c=window.SystemCore,V=window.SchoolV7,{state:s,$,esc:e}=c;
const kinds={students:'دانش‌آموزان',teachers:'دبیران',classes:'کلاس‌ها',scores:'نمرات',averages:'معدل‌ها',attendance:'حضور و غیاب',homework:'تکالیف',exams:'آزمون‌ها',exam_results:'نتایج آزمون',discipline:'انضباط',behavior:'رفتار',objections:'اعتراض‌ها',extracurricular:'فوق‌برنامه‌ها',forms:'پاسخ فرم‌ها',polls:'نظرسنجی‌ها'};
const columns={full_name:'نام و نام خانوادگی',national_id:'کد ملی',role:'نقش',active:'حساب فعال',title:'عنوان',student_id:'دانش‌آموز',user_id:'کاربر',class_id:'کلاس',grade_id:'پایه',subject_id:'درس',teacher_id:'دبیر',academic_year:'سال تحصیلی',period:'نوبت',continuous_score:'تکوینی',final_score:'پایانی',lesson_score:'نمره نهایی',average:'معدل',completed:'نمرات کامل',attendance_date:'تاریخ',status:'وضعیت',delay_minutes:'دقیقه',note:'یادداشت',score:'نمره',total_score:'نمره کل',max_score:'بارم کل',event_date:'تاریخ رویداد',event_type:'نوع',points:'امتیاز',reason:'علت',teacher_response:'پاسخ دبیر',start_at:'شروع',end_at:'پایان',submitted_at:'تاریخ ارسال',registered_at:'تاریخ ثبت‌نام',anonymous:'ناشناس',created_at:'تاریخ ایجاد'};
const personKeys=['student_id','teacher_id','user_id'];
V.reportCell=(key,value)=>{
if(value===null||value===undefined)return '—';if(personKeys.includes(key))return c.userName(value);
if(key==='class_id')return c.className(value);if(key==='subject_id')return c.subjectName(value);if(key==='grade_id')return c.byId(s.grades,value)?.title||'—';
if(key.endsWith('_at'))return V.datetime(value);if(['attendance_date','event_date'].includes(key))return V.date(value+'T12:00:00Z');
if(['status','role','event_type'].includes(key))return V.label(value);if(typeof value==='boolean')return value?'بله':'خیر';return String(value);};
V.exportRows=async(headers,rows,title)=>{
const XLSX=await c.ensureSheetJS(),book=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet([headers,...rows]);
sheet['!cols']=headers.map(()=>({wch:24}));sheet['!autofilter']={ref:XLSX.utils.encode_range({s:{r:0,c:0},e:{r:rows.length,c:headers.length-1}})};
book.Workbook={Views:[{RTL:true}]};XLSX.utils.book_append_sheet(book,sheet,'گزارش');
XLSX.writeFile(book,'system-'+title.replace(/[\\/:*?"<>|]/g,'-')+'.xlsx',{compression:true});};
V.routes.reports=async()=>{
let page=0,lastRows=[],keys=[],total=0;
const schoolSettings=await V.query(s.sb.from('school_settings').select('school_name').eq('id',true).single());
const schoolName=schoolSettings.school_name==='سامانه مدرسه'?c.cfg.SCHOOL_NAME:schoolSettings.school_name;
const initial=V.reportKind||'attendance';V.reportKind=null;
V.page('گزارش‌ها','گزارش‌های مجاز شما با خروجی Excel و چاپ A4 / PDF',`<div class="card no-print"><div class="form-grid">${V.select('reportKind','نوع گزارش',V.options(kinds),initial)}${V.select('rfRange','بازه گزارش',V.options({custom:'انتخابی',day:'روزانه',week:'هفتگی',month:'ماهانه',year:'سالانه'}))}${V.field('rfYear','سال تحصیلی','text','',false)}${V.select('rfGrade','پایه',s.grades,'',true)}${V.select('rfClass','کلاس',V.classOptions(),'',true)}${V.select('rfSubject','درس',s.subjects,'',true)}${V.select('rfTeacher','دبیر',V.personOptions('teacher'),'',true)}${V.select('rfStudent','دانش‌آموز',V.personOptions('student'),V.focusStudent||'',true)}${V.field('rfFrom','از تاریخ (شمسی)','text','',false)}${V.field('rfTo','تا تاریخ (شمسی)','text','',false)}${V.field('rfStatus','وضعیت','text','',false)}</div>${V.toolbar(V.button('loadReport','تهیه گزارش')+V.button('exportReport','Excel','btn-ghost')+V.button('printReportV7','چاپ / PDF','btn-ghost')+(V.staff()?V.button('absenceAlerts','غیبت زیاد','btn-ghost'):''))}<p class="hint">نمونه تاریخ: ۱۴۰۵/۰۷/۱۰. وضعیت: حاضر، غایب، موجه، غیرموجه، تأخیر، تأییدشده، در انتظار، ردشده.</p></div><section class="card v7-print-sheet"><div class="v7-report-heading"><img src="./assets/icons/logo.svg" alt="نشان مدرسه"><div><h2 id="reportHeading">گزارش</h2><p>${e(schoolName||'سامانه مدرسه')}</p></div><small>${V.date(new Date())}</small></div><p id="reportFilters" class="muted"></p><div id="reportRows"></div><div id="reportPager"></div></section>`);
function filters(){const out={};for(const [id,key] of [['rfYear','academic_year'],['rfGrade','grade_id'],['rfClass','class_id'],['rfSubject','subject_id'],['rfTeacher','teacher_id'],['rfStudent','student_id']])if(V.value(id))out[key]=V.value(id);
if(V.value('rfFrom'))out.from=V.gregorian(V.value('rfFrom'));if(V.value('rfTo'))out.to=V.gregorian(V.value('rfTo'));
if(V.value('rfStatus')){const raw=V.value('rfStatus');const aliases={'موجه':'excused','غیبت موجه':'excused','غیرموجه':'unexcused','غیبت غیرموجه':'unexcused','تأییدشده':'approved','ردشده':'rejected','در انتظار':'pending'};out.status=aliases[raw]||Object.keys(V.labels).find(k=>V.labels[k]===raw)||raw;}
return out;}
async function draw(){const kind=V.value('reportKind'),f=filters(),r=await V.rpc('school_report',{p_kind:kind,p_filters:f,p_offset:page*100,p_limit:100});lastRows=r.rows;total=r.total;
keys=Object.keys(columns).filter(key=>r.rows.some(row=>row[key]!==undefined));$('#reportHeading').textContent=kinds[kind];
$('#reportFilters').textContent=[['rfYear','سال'],['rfGrade','پایه'],['rfClass','کلاس'],['rfSubject','درس'],['rfTeacher','دبیر'],['rfStudent','دانش‌آموز'],['rfFrom','از'],['rfTo','تا'],['rfStatus','وضعیت']].filter(([id])=>V.value(id)).map(([id,label])=>label+': '+($('#'+id).tagName==='SELECT'?$('#'+id).selectedOptions[0]?.textContent:$('#'+id).value)).join(' · ')||'همه موارد مجاز';
$('#reportRows').innerHTML=c.table(keys.map(k=>columns[k]),r.rows.map(row=>'<tr>'+keys.map(k=>`<td>${e(V.reportCell(k,row[k]))}</td>`).join('')+'</tr>'));
$('#reportPager').innerHTML=V.pager(page,total,100);$('#prevPage').disabled=page===0;$('#nextPage').disabled=(page+1)*100>=total;V.bind('#prevPage',async()=>{page--;await draw();});V.bind('#nextPage',async()=>{page++;await draw();});}
$('#rfRange').onchange=()=>{const range=V.value('rfRange');if(range==='custom')return;
let from=new Date(V.today()+'T12:00:00Z'),to=new Date(from);const [year,month]=V.shamsi(from).split('/').map(Number);
if(range==='week'){from.setUTCDate(from.getUTCDate()-(from.getUTCDay()+1)%7);to=new Date(from);to.setUTCDate(to.getUTCDate()+6);}
if(range==='month'){from=new Date(V.gregorian(`${year}/${month}/1`)+'T12:00:00Z');to=new Date(V.gregorian(`${month===12?year+1:year}/${month===12?1:month+1}/1`)+'T12:00:00Z');to.setUTCDate(to.getUTCDate()-1);}
if(range==='year'){from=new Date(V.gregorian(`${year}/1/1`)+'T12:00:00Z');to=new Date(V.gregorian(`${year+1}/1/1`)+'T12:00:00Z');to.setUTCDate(to.getUTCDate()-1);}
$('#rfFrom').value=V.shamsi(from);$('#rfTo').value=V.shamsi(to);};
V.bind('#absenceAlerts',async()=>{const from=V.value('rfFrom')?V.gregorian(V.value('rfFrom')):V.gregorian(V.shamsi().split('/')[0]+'/1/1'),to=V.value('rfTo')?V.gregorian(V.value('rfTo')):V.today();const rows=await V.rpc('get_absence_alerts',{p_from:from,p_to:to});c.modal('دانش‌آموزان با غیبت زیاد',c.table(['دانش‌آموز','کل','موجه','غیرموجه','تأخیر'],rows.map(x=>`<tr><td>${e(x.full_name)}</td><td>${x.total}</td><td>${x.excused}</td><td>${x.unexcused}</td><td>${x.late}</td></tr>`)),async()=>{},'بستن');});
V.bind('#loadReport',async()=>{page=0;await draw();});V.bind('#exportReport',async()=>{
const kind=V.value('reportKind'),f=filters();let rows=[],offset=0,r;
do{r=await V.rpc('school_report',{p_kind:kind,p_filters:f,p_offset:offset,p_limit:200});rows.push(...r.rows);offset+=200;}while(offset<r.total);
const exportKeys=Object.keys(columns).filter(k=>rows.some(row=>row[k]!==undefined));if(!rows.length)throw new Error('گزارش خالی است.');
await V.exportRows(exportKeys.map(k=>columns[k]),rows.map(row=>exportKeys.map(k=>V.reportCell(k,row[k]))),kinds[kind]);});
V.bind('#printReportV7',async()=>{
const kind=V.value('reportKind'),f=filters();let rows=[],offset=0,r;do{r=await V.rpc('school_report',{p_kind:kind,p_filters:f,p_offset:offset,p_limit:200});rows.push(...r.rows);offset+=200;}while(offset<r.total);
const printKeys=Object.keys(columns).filter(k=>rows.some(row=>row[k]!==undefined));$('#reportRows').innerHTML=c.table(printKeys.map(k=>columns[k]),rows.map(row=>'<tr>'+printKeys.map(k=>`<td>${e(V.reportCell(k,row[k]))}</td>`).join('')+'</tr>'));await document.fonts.ready;window.print();await draw();});await draw();};
V.reportData=(data,classId=null,subjects=[])=>{
const selected=classId||data.classes?.[0]?.id,groups=new Map(subjects.map(x=>[x.id,[]]));
for(const score of data.scores){if(selected&&score.class_id!==selected)continue;if(!groups.has(score.subject_id))groups.set(score.subject_id,[]);groups.get(score.subject_id).push(score);}
const rows=[...groups].map(([id,items])=>{const p1=items.find(x=>String(x.period).includes('اول')),p2=items.find(x=>String(x.period).includes('دوم')),a=p1?.lesson_score==null?null:Number(p1.lesson_score),b=p2?.lesson_score==null?null:Number(p2.lesson_score);return {id,p1,p2,first:a,second:b,annual:a!==null&&b!==null?(a+b)/2:null};});
const average=values=>{const complete=values.filter(v=>v!==null);return complete.length?complete.reduce((a,b)=>a+b,0)/complete.length:null;};
return {rows,first:average(rows.map(x=>x.first)),second:average(rows.map(x=>x.second)),annual:average(rows.map(x=>x.annual))};};
V.renderReport=async student=>{
const [data,settings]=await Promise.all([V.rpc('get_student_profile',{p_student:student}),V.query(s.sb.from('school_settings').select('*').eq('id',true).single())]);
if(!data.profile)throw new Error('ACCESS_DENIED');
if(s.profile.role==='student'&&!settings.report_cards_open){V.page('کارنامه','', '<div class="card empty">نمایش کارنامه توسط مدیر بسته است.</div>');return;}
const p=data.profile,cls=data.classes.find(x=>V.reportStudent===student&&x.id===V.reportClass)||data.classes[0],grade=c.byId(s.grades,cls?.grade_id);
V.reportStudent=student;V.reportClass=cls?.id;
const subjects=s.subjects.filter(x=>x.grade_id===cls?.grade_id&&(s.profile.role!=='teacher'||s.assignments.some(a=>a.class_id===cls.id&&a.subject_id===x.id&&a.teacher_id===s.profile.id)));
const result=V.reportData(data,cls?.id,subjects),attendance=data.class_summaries?.find(x=>x.class_id===cls?.id)||{total:0,unexcused:0,late:0},discipline=data.discipline.find(x=>x.class_id===cls?.id),pass=Number(settings.passing_score),f=x=>x===null||x===undefined?'—':Number(x).toFixed(2),delta=result.first!==null&&result.second!==null?result.second-result.first:null;
const complete=result.rows.length>0&&result.rows.every(x=>x.annual!==null),overall=!complete?'نمره ناقص':result.rows.every(x=>x.annual>=pass)?'قبول':'نیاز به تلاش';
V.page('کارنامه تحصیلی',p.full_name,`<div class="card no-print">${V.select('reportClass','کلاس و سال تحصیلی',data.classes.map(x=>({id:x.id,title:x.title+' · '+x.academic_year})),cls?.id)}${V.toolbar(V.button('printSchoolReport','چاپ / PDF')+V.button('exportSchoolReport','Excel','btn-ghost'))}</div><section class="report-sheet v7-print-sheet"><div class="report-title"><img class="v7-report-logo" src="./assets/icons/logo.svg" alt="نشان مدرسه"><div><h2>کارنامه تحصیلی دانش‌آموز</h2><p>${e(settings.school_name==='سامانه مدرسه'?c.cfg.SCHOOL_NAME:settings.school_name)}</p></div><div class="report-year">سال تحصیلی<br><strong>${e(cls?.academic_year||'—')}</strong></div></div><div class="report-meta"><span>نام: ${e(p.full_name)}</span><span>کد ملی: ${e(p.national_id)}</span><span>پایه: ${e(grade?.title||'—')}</span><span>کلاس: ${e(cls?.title||'—')}</span><span>نوبت اول و دوم</span></div>${c.table(['درس','تکوینی اول','پایانی اول','نهایی اول','تکوینی دوم','پایانی دوم','نهایی دوم','سالانه','وضعیت','اعتراض'],result.rows.map(x=>`<tr><td>${e(c.subjectName(x.id))}</td><td>${f(x.p1?.continuous_score)}</td><td>${f(x.p1?.final_score)}</td><td>${f(x.first)}</td><td>${f(x.p2?.continuous_score)}</td><td>${f(x.p2?.final_score)}</td><td>${f(x.second)}</td><td>${f(x.annual)}</td><td>${x.annual===null?'نمره ناقص':x.annual>=pass?'قبول':'نیاز به تلاش'}</td><td class="no-print">${s.profile.role==='student'&&settings.objections_open&&(x.p2?.id||x.p1?.id)?`<button class="btn btn-ghost v7-objection" data-score="${x.p2?.id||x.p1?.id}" data-subject="${x.id}">اعتراض</button>`:'—'}</td></tr>`))}<div class="report-summary"><div><small>معدل نوبت اول</small><strong>${f(result.first)}</strong></div><div><small>معدل نوبت دوم</small><strong>${f(result.second)}</strong></div><div><small>تغییر معدل</small><strong>${delta===null?'—':(delta>0?'+':'')+f(delta)}</strong></div><div><small>معدل سالانه</small><strong>${f(result.annual)}</strong></div><div><small>وضعیت کلی</small><strong>${overall}</strong></div></div><div class="v7-trend" role="img" aria-label="مقایسه معدل دو نوبت">${[['نوبت اول',result.first],['نوبت دوم',result.second]].map(([title,value])=>`<div><span>${title}</span><progress max="20" value="${value??0}"></progress><b>${f(value)}</b></div>`).join('')}</div><div class="report-meta"><span>غیبت کل: ${attendance.total}</span><span>غیبت غیرموجه: ${attendance.unexcused}</span><span>تأخیر: ${attendance.late}</span><span>انضباط: ${discipline?.score??'—'}</span><span>رفتار مثبت: ${attendance.positive||0}</span><span>رفتار منفی: ${attendance.negative||0}</span></div><div class="report-signatures"><span>امضای مدیر مدرسه</span><span>امضای دبیر / ولی دانش‌آموز</span></div></section>`);
$('#reportClass').onchange=async()=>{V.reportClass=V.value('reportClass');try{await V.renderReport(student);}catch(error){c.toast(c.errText(error),true);}};
V.bind('#printSchoolReport',async()=>{await document.fonts.ready;window.print();});V.bind('#exportSchoolReport',()=>V.exportRows(['درس','تکوینی اول','پایانی اول','نهایی اول','تکوینی دوم','پایانی دوم','نهایی دوم','سالانه'],result.rows.map(x=>[c.subjectName(x.id),x.p1?.continuous_score??'',x.p1?.final_score??'',x.first??'',x.p2?.continuous_score??'',x.p2?.final_score??'',x.second??'',x.annual??'']),'کارنامه'));
V.bind('.v7-objection',b=>c.studentObjectionModal(b.dataset.score,b.dataset.subject));};
V.routes.report=()=>V.renderReport(s.profile.id);
V.routes['student-report']=()=>V.renderReport(V.focusStudent||s.profile.id);
})();
