-- v8 / 01: Security, audit log, password lifecycle and central grading settings
-- Non-destructive: existing rows and credentials are preserved.
set role postgres;

alter table public.profiles
  add column if not exists must_change_password boolean not null default false,
  add column if not exists password_changed_at timestamptz;

alter table public.school_settings
  add column if not exists passing_score numeric(5,2) not null default 10
    check (passing_score between 0 and 20);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null check (action in ('INSERT','UPDATE','DELETE')),
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);
create index if not exists idx_audit_logs_user on public.audit_logs(user_id,created_at desc);
create index if not exists idx_audit_logs_table_record on public.audit_logs(table_name,record_id);

alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_manager_read on public.audit_logs;
create policy audit_logs_manager_read on public.audit_logs
for select to authenticated
using (public.is_manager());

-- No authenticated INSERT/UPDATE/DELETE policies are intentionally created.
revoke insert, update, delete on public.audit_logs from authenticated;
grant select on public.audit_logs to authenticated;

create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_old jsonb;
  v_new jsonb;
  v_record text;
begin
  if tg_op='INSERT' then
    v_new:=to_jsonb(new);
    v_record:=coalesce(v_new->>'id',v_new->>'student_id',v_new->>'user_id');
  elsif tg_op='UPDATE' then
    v_old:=to_jsonb(old);
    v_new:=to_jsonb(new);
    v_record:=coalesce(v_new->>'id',v_new->>'student_id',v_new->>'user_id');
  else
    v_old:=to_jsonb(old);
    v_record:=coalesce(v_old->>'id',v_old->>'student_id',v_old->>'user_id');
  end if;

  insert into public.audit_logs(user_id,action,table_name,record_id,old_data,new_data)
  values(auth.uid(),tg_op,tg_table_name,v_record,v_old,v_new);

  return case when tg_op='DELETE' then old else new end;
end
$$;

revoke all on function public.audit_row_change() from public;
grant execute on function public.audit_row_change() to postgres, service_role;

-- Helper safely attaches audit triggers only to tables that exist.
create or replace function public.attach_audit_trigger(p_table text)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if to_regclass('public.'||quote_ident(p_table)) is null then return; end if;
  execute format('drop trigger if exists trg_audit_%I on public.%I',p_table,p_table);
  execute format(
    'create trigger trg_audit_%I after insert or update or delete on public.%I for each row execute function public.audit_row_change()',
    p_table,p_table
  );
end
$$;

select public.attach_audit_trigger(x)
from unnest(array[
  'profiles','scores','teacher_assignments','class_students',
  'discipline_scores','school_settings'
]) as x;

create or replace function public.confirm_password_changed()
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'UNAUTHORIZED'; end if;
  update public.profiles
  set must_change_password=false,
      password_changed_at=now()
  where id=auth.uid();
end
$$;

grant execute on function public.confirm_password_changed() to authenticated;

-- Authenticated users may read the flag on their own profile through existing RLS.
-- Existing users are not forcibly marked because we cannot reliably know whether
-- they still use the historical initial password. New users are marked by admin-user.

create or replace function public.account_security_state()
returns jsonb
language sql
stable
security invoker
set search_path=public
as $$
  select jsonb_build_object(
    'must_change_password',coalesce(p.must_change_password,false),
    'password_changed_at',p.password_changed_at,
    'role',p.role
  )
  from public.profiles p
  where p.id=auth.uid()
$$;

grant execute on function public.account_security_state() to authenticated;

select
  has_table_privilege('authenticated','public.audit_logs','SELECT') as audit_read_granted,
  has_function_privilege('authenticated','public.confirm_password_changed()','EXECUTE') as password_rpc_granted;
